spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.14.18:3306/studentandcompany?characterEncoding=utf8&useSSL=false
    username: root
    password: uAiqwVwjJ8-i
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: news-consumer
debug: false
logging:
  level:
    com.f22pkj31.community: debug
server:
  port: 8012