spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/community?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: post-provider
debug: false
logging:
  level:
    com.f22pkj31.community: debug
server:
  port: 8003
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true