spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: file-api
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,lasspath:/static/,classpath:/public/,file:${resources_path}
debug: false
logging:
  level:
    com.f22pkj31.community: debug
server:
  port: 8010
resources_path: C:\\Users\\11362\\file\\
#resources_path: /Users/bo.fan/file/