spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/community?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: news-provider
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,lasspath:/static/,classpath:/public/,file:${resources_path}
debug: false
logging:
  level:
    com.f22pkj31.community: debug
server:
  port: 8002
  tomcat:
    basedir: C:\\Users\\11362\\temp\\
resources_path: C:\\Users\\11362\\file\\
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true