spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/community?useUnicode=true&useSSL=false&characterEncoding=utf8
      username: root
      password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: blog-provider
server:
  port: 8001
debug: false
logging:
  level:
    com.f22pkj31.community: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
